### ISSUE TITLE
anaconda python 3.7 comptability

### ISSUE THREAD

**Issue by llvll0hsen** [discogs/discogs_client#103]
I've tried to use anaconda to install the package and it tells me there is version mismatch to my python version (3.7). I want to verify this and ask if there is any plan to add support for the python 3.7.

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
