### ISSUE TITLE
Neither of the authorization scemes work.

### ISSUE THREAD

**Issue by sngreen** [discogs/discogs_client#104]
>>> d.get_authorize_url()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sergey\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discogs_client\client.py", line 63, in get_authorize_url
    raise AuthorizationError('Could not get request token.', status_code, content)
discogs_client.exceptions.AuthorizationError: 401: Could not get request token. Response: b'Invalid consumer.'

**Comment by sngreen** [comment]
I assume the key is the user and the secret-here is the password. If yes,
>>> d.set_consumer_key('key-here', 'secret-here')
>>> d.get_authorize_url()

meh .... Response: b'Invalid consumer.'

Good idea, but till it works ...

**Comment by dijksterhuis** [comment]
> I assume the key is the user and the secret-here is the password.

No. You need to set up an Application on the below page, which can provide you with a consumer key and secret:
https://www.discogs.com/settings/developers

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
