### ISSUE TITLE
Some albums not found in the database

### ISSUE THREAD

**Issue by Yojimbo94** [discogs/discogs_client#108]
Hello !
Been using the API since yesterday and i was able to retrieve the datas i wanted to for a lot of albums.
But for one album, even with the exact same name and artist name, the search function returns an empty array.

i've tried searching with the exact same name on the website and it found it.
Album : _The Emancipation Procrastination_
Artist : _Christian Scott aTunde Adjuah_

Here is the search i'm talking about : 
[https://www.discogs.com/search/?q=Christian+Scott+aTunde+Adjuah+The+Emancipation+Procrastination](url)

As you can see, there are 2 masters, 5 releases and other things.

`
alb_title = 'The Emancipation Procrastination'
alb_artist = 'Christian Scott aTunde Adjuah'
results = d.search(title=alb_title, artist=alb_artist, type='master')
results = d.search(title=alb_title, artist=alb_artist, type='release')
results = d.search(title=alb_title, artist=alb_artist)
print(results.page(1))
`
Those three different results print the same thing : an empty array.

It is possible to find the album if i only have the album title or the first part of the artist name (Christian Scott) but there must be some kind of problem if it can't find it with the exact artist/album name

thanks

**Comment by Yojimbo94** [comment]
I said that it was the only one but it is not, actually.
And some others are not working, but they all have in common (expanded edition) or those kind of things in their titles

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
