### ISSUE TITLE
Should "200 OK" replies ever be considered errors?

### ISSUE THREAD

**Issue by marado** [discogs/discogs_client#27]
See the comment: https://github.com/discogs/discogs_client/commit/f77e060ba3aa32907dcf87520c5006e10cb5b75e#commitcomment-6280087

Basically, we're assuming that if a response has no content an exception should be raised, even if the response http_code is an 200 OK. I'm not saying this is actually a bug, just that it might be... the API documentation isn't explicit about this.

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
