### ISSUE TITLE
Non-ASCII searches fail because python-oauth2 is broken

### ISSUE THREAD

**Issue by sampsyo** [discogs/discogs_client#40]
Searching for a non-ASCII term causes this error:

    >>> import discogs_client
    >>> c = discogs_client.Client('user_agent', 'bogus_key', 'bogus_secret')
    >>> c.search(u'caf\xe9'.encode('utf8')).page(1)
    Traceback (most recent call last):
    [ ... snip ... ]
      File "/usr/local/lib/python2.7/site-packages/oauth2/__init__.py", line 442, in to_url
        urllib.urlencode(query, True), fragment)
      File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1357, in urlencode
        l.append(k + '=' + quote_plus(str(elt)))
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-4: ordinal not in range(128)

This is due to a known bug in python-oauth2: https://github.com/simplegeo/python-oauth2/issues/154. That library, unfortunately, appears to be abandoned: [the last commit](https://github.com/simplegeo/python-oauth2/commit/a83f4a297336b631e75cba102910c19231518159) was in 2011 (c.f. [this lament](http://pydanny.com/the-sorry-state-of-python-oauth-providers.html) over the sorry state of Python OAuth libraries).

It's worth noting that this was not an issue when sending non-ASCII requests *without* OAuth authentication because they don't go through the broken library. This has only come up recently because the search API now requires authentication, so we're now these previously-working requests are now hitting this bug.

As unattractive as it seems, I think the only solution may be to move to a more modern OAuth library. Personally, I've had success with [rauth](https://github.com/litl/rauth).

**Comment by vindarel** [comment]
Hello there ! I'm looking forward to using the discogs client. Any news on this issue ?

Thanks

**Comment by rodneykeeling** [comment]
@vindarel We've just released a bug fix that should resolve this issue. Please take a look and let us know if you have further issues.

Thanks!

**Comment by vindarel** [comment]
Great news ! I'll tell you as soon as I test it.
