### ISSUE TITLE
Handle socket, httplib, and json exceptions

### ISSUE THREAD

**Issue by sampsyo** [discogs/discogs_client#44]
Currently, `socket.error` exceptions raised during API requests are unhandled and passed through to the client. For consistency, the library should probably catch `socket.error`s and re-raise `discogs_client.exceptions.HTTPError`s.

See https://github.com/sampsyo/beets/issues/1299 for a traceback arising from an unexpected socket closure.

**Comment by sampsyo** [comment]
Exceptions from `httplib` also need to be handled (see https://github.com/sampsyo/beets/issues/1305). Note that both of these are raised from within oath2, which really should be handling these but is unmaintained (see #40).

**Comment by sampsyo** [comment]
Sorry for all the updates, but there's a third category of exception that needs to be caught: JSON decoding errors. This time, we can't blame oauth2 since it is raised directly from client.py. :smiley:

Traceback: https://github.com/sampsyo/beets/issues/1305#issuecomment-72802083

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
