### ISSUE TITLE
Put a new tag on master

### ISSUE THREAD

**Issue by brunal** [discogs/discogs_client#45]
Hi,
As mentioned in PR #43 I believe it could be time to push a new tag (e.g. 2.0.3 or 2.1.0) to allow python3 projects using discogs_client to put it in their setup.py

**Comment by rodneykeeling** [comment]
Thanks @brunal, a new version on Github has been added, and the project has been updated on PyPi: https://pypi.python.org/pypi/discogs-client/2.1.0

Cheers,
Rodney
