### ISSUE TITLE
How to get just the singles?

### ISSUE THREAD

**Issue by rvvincelli** [discogs/discogs_client#67]
Hi guys, sorry if I open an issue for what is actually a question, but I think it's just easier.

How can I retrieve just the singles/EPs for a given artist?

I've tried like:

`engine.search('Ricardo Villalobos', type='releases', subtype='singles-eps')`

and the URL is formed correctly, but result set fetched is identical.

My guess is that I just have to refer to the `tracklist` - both the `Master` and `Release` entities have this. 

Thanks in advance!

**Comment by rodneykeeling** [comment]
Hi @rvvincelli,

There currently isn't a way to select that subset of data; you would have to do the filtering manually after fetching all of the Artist's Releases.

Thanks,
Rodney
