### ISSUE TITLE
Please add support for lists

### ISSUE THREAD

**Issue by drfindley** [discogs/discogs_client#68]
I just saw these were added 16 hours ago, but being able to retrieve all lists for a user or a list in general like the API added would be nice.

**Comment by susansalkeld** [comment]
We have recently added to the API retrieving all lists for a user [https://www.discogs.com/developers/#page:user-lists,header:user-lists-user-lists](here). We will add this endpoint to the discogs_client soon. Cheers!

**Comment by stefanvdw1** [comment]
Following up on this ticket. Has the capability to retrieve user lists and items from lists been added yet? It would be great to have this!

**Comment by dijksterhuis** [comment]
There’s a pull request that’s been waiting for acceptance into master for around 2 years:
https://github.com/discogs/discogs_client/pull/83

**Comment by stefanvdw1** [comment]
I've submitted a posted on the API section of the forum, hopefully that will speed this up.

**Comment by Knusper** [comment]
Mh... Still nothing. Can you please link to the post in the forum?

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
