### ISSUE TITLE
Please add support for adding/removing/rating releases to collections

### ISSUE THREAD

**Issue by drfindley** [discogs/discogs_client#69]
You can get releases from collection folders, but you can't add, remove or rate releases.

**Comment by susansalkeld** [comment]
We have added a ticket for this. In the meantime, if you want to use the API endpoint for this functionality, the details are [https://www.discogs.com/developers/#page:user-collection,header:user-collection-change-rating-of-release](here).

**Comment by edgeded** [comment]
unfortunately this page is not available anymore. is there an alternative to that?

**Comment by rodneykeeling** [comment]
@edgeded It looks like there's a problem with Github and that URL. Copying and pasting (instead of directly clicking) the URL should work still.

**Comment by edgeded** [comment]
thanks!

**Comment by JOJ0** [comment]
I opened a pull-request for one of the mentioned features in this issue (add release to collection): https://github.com/discogs/discogs_client/pull/106

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
