### ISSUE TITLE
search option with accents/special markings removed?

### ISSUE THREAD

**Issue by hubenjm** [discogs/discogs_client#72]
When using `d.search(album_name, type='release')`, sometimes the album_name in the database uses special accented characters. For example, the release "Béla Fleck & the Flecktones - UFO Tofu". The problem is that when trying `d.search("Bela Fleck & The Flecktones - UFO Tofu", type='release')`, the result list is empty. It would be nice if there could be some option to apply a string transformation in the backend, such as [(https://pypi.python.org/pypi/Unidecode)], which would allow for a slightly fuzzier string match.

I should add that I have no idea how the backend works, so I apologize if this kind of idea would not make any sense.

**Comment by rodneykeeling** [comment]
Hi @hubenjm,

This appears to be an issue with our internal search system (the same issue exists on the www website). We will be getting this fixed as soon as we can!

Thanks for the report,
Rodney
