### ISSUE TITLE
Changing per_page elements to max value? 

### ISSUE THREAD

**Issue by systems-rebooter** [discogs/discogs_client#73]
Hi!

I am afraid of wasting API calls because of rate_limiting.

One of possible solutions is to change `per_page` elements to maximum value. 

How can I do this on app side without changing `self._per_page = 50` value in `discogs_client/models.py`? 

Or maybe there are some better workarounds

Thanks!

**Comment by rodneykeeling** [comment]
Yes, the current method would be to set the `_per_page` value on any paginated response object.

e.g.,
```python
rels = ds.artist(1).releases
rels._per_page = 100
```

**Comment by systems-rebooter** [comment]
Cool! Thanks, @rodneykeeling
