### ISSUE TITLE
Add tag 2.2.1 which is apparently released

### ISSUE THREAD

**Issue by inglor** [discogs/discogs_client#75]
There's no tag for 2.2.1 but there's a version out for that https://pypi.python.org/pypi/discogs-client

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
