### ISSUE TITLE
discogs_client doesnt honor Discogs rate limits

### ISSUE THREAD

**Issue by T-101** [discogs/discogs_client#82]
Discogs has recently lowered their rate limit from 240 reqs/min to 60 reqs/min. This obviously means that some applications will hit the limit quite soon.

**Comment by RobSis** [comment]
I second this. Looking at the code, it seems that the client doesn't honour the limits at all...

It would be great to have limiter based on X-Discogs-Ratelimit headers...

**Comment by madCode** [comment]
I can't find a place in the code that even returns the ratelimit headers. Hopefully I'm just not looking in the right place. But if they really aren't accessible from the python library, that renders the library more or less useless.

**Comment by RobSis** [comment]
Well, that's too harsh ;) I find the library very useful, although not finished. I'm currently working on the rate-limiting, but I'm still not sure what should the best strategy be.

The bigger problem seems to be inactivity of its developers, but I hope that's just temporary ;)

**Comment by VoyagerPunk** [comment]
Looks like the rate limit is returned in headers as documented [here][1], perhaps it is best to add an attribute to the client object which stores the ratelimit and ratelimit remaining. This can then be used in the `Client._request` logic to limit requests accordingly.

[1]: https://www.discogs.com/developers/#page:home,header:home-rate-limiting

**Comment by VoyagerPunk** [comment]
This may not be prioritized because it is documented what the limits values are so your application layer can account for this (ie take a timestamp at time of first request and make sure for the next minute the limit isn't reached) and, while it would not be the hardest change to make it would involve altering some of the wrapper behavior, which may require a fair amount of work to avoid issues with the tests etc. Because of this the developers may not see this as a bug report but a feature request, and it seems that new features aren't a priority for the client.

**Comment by alifhughes** [comment]
Any chance of this being looked into again? I understand @doomb0t 's point completely, that it is implied we are expected to manage this but it would be good to know for certain. Especially as there are 3 PRs open that could fix this and close [issue 92](https://github.com/discogs/discogs_client/issues/92) as well as this one. If it isn't, I guess are we expected to fork and include changes in our forks? 
- [PR109](https://github.com/discogs/discogs_client/pull/109)
- [PR89](https://github.com/discogs/discogs_client/pull/89)
- [PR102](https://github.com/discogs/discogs_client/pull/102)

**Comment by alifhughes** [comment]
@brephophagist bump

**Comment by JOJ0** [comment]
Thanks for mentioning it here @alifhughes. Little update on this one: https://www.discogs.com/forum/thread/818998

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
