### ISSUE TITLE
Client' object has no attribute 'Release'

### ISSUE THREAD

**Issue by jkemege** [discogs/discogs_client#84]
why am I getting this error?

> c:\discogs\tl_out.py(12)<module>()
-> release = ds.Release(380484)
(Pdb) n
AttributeError: "'Client' object has no attribute 'Release'"

with this Python code:
import discogs_client as discogs
discogs.user_agent = 'jkkGetTrackLists/0.1'
ds = discogs.Client(discogs.user_agent, user_token="UyRNtkkPucDKrtMluzIRAvNoWzHjsLLRtfYvsKeG")
release = ds.Release(380484)
print(release.title)
for item in release.tracklist:
    print(item)

Keven

**Comment by jkemege** [comment]
Plus when I change the offending line to discogs_client(because that's where Release is at), I get this error with regard to  __init__ arguments....:

> c:\discogs\tl_out.py(12)<module>()
-> release = discogs.Release(380484)
(Pdb) n
TypeError: '__init__() takes exactly 3 arguments (2 given)'

not sure what to do to fix this condition??

**Comment by rodneykeeling** [comment]
Hi Keven,

You'll need to change this:
`release = ds.Release(380484)`
to this:
`release = ds.release(380484)`

Cheers,
Rodney

**Comment by jkemege** [comment]
All is ok now...
I copied this code from somewhere and thought it was good
R to r worked... I thought it was something to do with the discogs_client install...
Much thanks!

Keven
