### ISSUE TITLE
Unable to set order shipping price

### ISSUE THREAD

**Issue by qwesda** [discogs/discogs_client#85]
Here is a minimal example to reproduce the error:

```import discogs_client

client = discogs_client.Client("<user_agent>", user_token="<user_token>")
order = client.order("<order_id>")
order.shipping = 9.9
order.save()
```

The response is 400: `'Expected mimetype of "application/json".'`

This happens because you set `headers['Content-Type'] = 'application/x-www-form-urlencoded'` in the post request https://github.com/discogs/discogs_client/blob/dc6551e5844d20a9da69e97c19afa8234f292d41/discogs_client/client.py#L102-L108.

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
