### ISSUE TITLE
Increase test coverage for network request fetchers

### ISSUE THREAD

**Issue by doomb0t** [discogs/discogs_client#90]
I noticed there aren't any tests for the fetchers which make calls to the api, this can be done by using [wsgi_intercept][1]  to intercept network requests and then returning statically coded responses much like you do currently with the other fetchers. At Adblock Plus we use wsgi_intercept in couple test suites like [here][2] and [here][3]. Even though we are using pytest it shouldn't be a problem to do this with unittest/nose and I would be happy to implement the tests and intercepts as well.

[1]: https://github.com/cdent/wsgi-intercept
[2]: https://github.com/adblockplus/cms/blob/master/tests/test_translations.py#L38-L46
[3]: https://github.com/adblockplus/sitescripts/blob/master/sitescripts/formmail/test/test_formmail2.py#L68-L87

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
