### ISSUE TITLE
Release CatNo

### ISSUE THREAD

**Issue by basil-lam** [discogs/discogs_client#91]
In a curl request for a particular release, I can see release.labels.catno. 
However, when using the client, release.labels only return items with the label ID and name, no other fields are provided

**Comment by JOJ0** [comment]
Alright, this is a very old question and you've probably figured it out already, but maybe it helps someone else and this issue can be finally closed: 

catno information via the client is found inside the labels data object/dict. eg. like this:

```
catno = release_obj.labels[0].data['catno']
```

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
