### ISSUE TITLE
Rate limit, how to get remaining?

### ISSUE THREAD

**Issue by apjavel** [discogs/discogs_client#92]
As per this page it is possible to retrieve Used and Remaining Rate Limit.
https://www.discogs.com/developers/#page:home,header:home-rate-limiting

Is it possible to get these from within the Python API?

It would be very useful, to avoid getting gateway timeout Exception.

**Comment by VoyagerPunk** [comment]
https://github.com/discogs/discogs_client/pull/89

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
