### ISSUE TITLE
Exclude appearances

### ISSUE THREAD

**Issue by oscarsidebo** [discogs/discogs_client#93]
Is there a way to get all actual releases by an artist, meaning to exclude any appearances on compilations etc. Would this be master releases?  For example when I go through a specific artist releases I get roughly 200 of them but on the discogs only 14 of them are the artist own releases and rest are just appearances.

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
