### ISSUE TITLE
Any way to get a release's exact release date?

### ISSUE THREAD

**Issue by SHxKM** [discogs/discogs_client#94]
All I see available is a simple "year" field.

Am I missing something?

**Comment by dijksterhuis** [comment]
I know the csv dumps include release date in the releases file (not the master file).

They are not clean dates though. Many different formats as assume is a text input. 

Wrt api I’m not sure. Not spent enough time near it recently.

**Comment by devonwalshe** [comment]
There is a property on the api response for releases called `released` that stores a date if present.

I've forked and updated the release class in `models.py`. Happy to submit a PR.

@SHxKM if you want to do this yourself:

1. clone the repo
2. add the line `released = SimpleField()` in the `Release` class in `models.py`
3. add the line `import discogs_client` in `__init__.py` (to get the imports working, pretty sure there is a better way to do this)
4. Install the package with `python -m pip install path/to/your/repo/discogs_client`
5. `import discogs_client` in python and any release you look up should have the `released` property.

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
