### ISSUE TITLE
Image is broken when its a gif

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [discogs/discogs_client#99]
Hey , 
I am making a webapp and i am using the https://api.discogs.com/database/search? endpoint. 
I am working with some fields and its working fine but i noticed a bug. 
When i want to display an image that ends with .gif the ouput is a broken link. I noticed that because i was having broken links and when i was debugging i saw 3 images that ended with .gif 
You guys knew that or not realy?

**Comment by vreon** [comment]
Hi, thank you for opening this issue.

Unfortunately, this project is no longer actively maintained, and today, we're archiving the repository and publishing the final version to PyPI.

We sincerely appreciate your contribution and regret that we weren't able to give it the attention it deserved.
